# Indian Start-Up Funding Analysis (2018 - 2021)

# Business Understanding

Main Objective of the Project

The primary objective of this project is to analyze the funding trends in the Indian start up ecosystem from 2018 to 2021.
By examining the data, we aim o identify patterns, trends and insights that can inform strategic decisions for entering the Indian start up market. Specifically, we will focus on understanding the amount of funding received by start ups, the type of investors involved and the sectors that attract the most investment.


Key Research Questions
1. How has the total amount of funding received by start-ups in India changed from 2018-2021?
2. Which sectors have received the most funding in each year?
3. Who are the top investors in the India start-up ecosystem from 2018-2021?
4. Which regions or cities in India are receiving the most start-up funding?
5. Does the stage align with the investment timeline?
6. How lon has the company been operating and how doeas this affect the amount of investment?

Importing Necessary Packages

In [2]:
import pyodbc
import pandas as pd
from dotenv import dotenv_values
import warnings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)


warnings.filterwarnings('ignore')

In [3]:
# . env file

server='dap-projects-database.database.windows.net'
database='dapDB'
username='LP1_learner'
password='Hyp0th3s!$T3$t!ng'

In [4]:
#Loading environment variables from .env into a dictionary

env_var = dotenv_values('.env')

#Getting credentials

server = env_var.get('server')
database = env_var.get('database')
username = env_var.get('username')
password = env_var.get('password')

conn = f'DRIVER={{SQL SERVER}};SERVER={server};DATABASE={database};UID={username};PWD={password};timeout=30'

In [5]:
#Connecting to the server

connection = pyodbc.connect(conn)

In [6]:
import pyodbc

try:
    connection = pyodbc.connect(conn)
    print("Connection successful!")
except pyodbc.Error as ex:
    sqlstate = ex.args[1]
    print(f"Connection failed: {sqlstate}")

Connection successful!

In [7]:
#Fetching from database

db_query = '''
            SELECT *
            FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_TYPE = 'BASE TABLE'
            '''

data = pd.read_sql(db_query, connection)
data

  TABLE_CATALOG TABLE_SCHEMA               TABLE_NAME  TABLE_TYPE
0         dapDB          dbo  LP1_startup_funding2021  BASE TABLE
1         dapDB          dbo  LP1_startup_funding2020  BASE TABLE

In [8]:
query_1 = '''
          SELECT * 
          FROM LP1_startup_funding2021
          '''

data_021 = pd.read_sql(query_1, connection)
data_021.head()

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage
0,Unbox Robotics,2019.0,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First","$1,200,000",Pre-series A
1,upGrad,2015.0,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management","$120,000,000",None
2,Lead School,2012.0,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital","$30,000,000",Series D
3,Bizongo,2015.0,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital","$51,000,000",Series C
4,FypMoney,2021.0,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal","$2,000,000",Seed

In [9]:
query_2 = '''
          SELECT * 
          FROM LP1_startup_funding2020
          '''


data_020 = pd.read_sql(query_2, connection)
data_020.head()

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,column10
0,Aqgromalin,2019.0,Chennai,AgriTech,Cultivating Ideas for Profit,"Prasanna Manogaran, Bharani C L",Angel investors,200000.0,None,None
1,Krayonnz,2019.0,Bangalore,EdTech,An academy-guardian-scholar centric ecosystem ...,"Saurabh Dixit, Gurudutt Upadhyay",GSF Accelerator,100000.0,Pre-seed,None
2,PadCare Labs,2018.0,Pune,Hygiene management,Converting bio-hazardous waste to harmless waste,Ajinkya Dhariya,Venture Center,NaN,Pre-seed,None
3,NCOME,2020.0,New Delhi,Escrow,Escrow-as-a-service platform,Ritesh Tiwari,"Venture Catalysts, PointOne Capital",400000.0,None,None
4,Gramophone,2016.0,Indore,AgriTech,Gramophone is an AgTech platform enabling acce...,"Ashish Rajan Singh, Harshit Gupta, Nishant Mah...","Siana Capital Management, Info Edge",340000.0,None,None

In [10]:
#To view all rows and columns without truncating

data_019 = pd.read_csv(r'C:\Users\Admin\Downloads\startup_funding2019.csv')
data_019.head()

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
0,Bombay Shaving,NaN,NaN,Ecommerce,Provides a range of male grooming products,Shantanu Deshpande,Sixth Sense Ventures,"$6,300,000",NaN
1,Ruangguru,2014.0,Mumbai,Edtech,A learning platform that provides topic-based ...,"Adamas Belva Syah Devara, Iman Usman.",General Atlantic,"$150,000,000",Series C
2,Eduisfun,NaN,Mumbai,Edtech,It aims to make learning fun via games.,Jatin Solanki,"Deepak Parekh, Amitabh Bachchan, Piyush Pandey","$28,000,000",Fresh funding
3,HomeLane,2014.0,Chennai,Interior design,Provides interior designing solutions,"Srikanth Iyer, Rama Harinath","Evolvence India Fund (EIF), Pidilite Group, FJ...","$30,000,000",Series D
4,Nu Genes,2004.0,Telangana,AgriTech,"It is a seed company engaged in production, pr...",Narayana Reddy Punyala,Innovation in Food and Agriculture (IFA),"$6,000,000",NaN

In [11]:

#Alternative to view all rows and columns without truncating

pd.options.display.max_columns = None
pd.options.display.max_rows = None


data_018 = pd.read_csv(r'C:\Users\Admin\Downloads\startup_funding2018.csv')
data_018.head()

,Company Name,Industry,Round/Series,Amount,Location,About Company
0,TheCollegeFever,"Brand Marketing, Event Promotion, Marketing, S...",Seed,250000,"Bangalore, Karnataka, India","TheCollegeFever is a hub for fun, fiesta and f..."
1,Happy Cow Dairy,"Agriculture, Farming",Seed,"₹40,000,000","Mumbai, Maharashtra, India",A startup which aggregates milk from dairy far...
2,MyLoanCare,"Credit, Financial Services, Lending, Marketplace",Series A,"₹65,000,000","Gurgaon, Haryana, India",Leading Online Loans Marketplace in India
3,PayMe India,"Financial Services, FinTech",Angel,2000000,"Noida, Uttar Pradesh, India",PayMe India is an innovative FinTech organizat...
4,Eunimart,"E-Commerce Platforms, Retail, SaaS",Seed,—,"Hyderabad, Andhra Pradesh, India",Eunimart is a one stop solution for merchants ...

# Data Manipulation

In [12]:
# Concatenate all datasets

combined_data = pd.concat([data_021, data_020, data_019, data_018], ignore_index=True)

In [13]:
# Preview of combined data

combined_data.head()

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,column10,Company/Brand,What it does,Amount($),Company Name,Industry,Round/Series,Location,About Company
0,Unbox Robotics,2019.0,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First","$1,200,000",Pre-series A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,upGrad,2015.0,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management","$120,000,000",None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Lead School,2012.0,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital","$30,000,000",Series D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bizongo,2015.0,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital","$51,000,000",Series C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FypMoney,2021.0,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal","$2,000,000",Seed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


# **Exploratory Data Analysis**

In [14]:
# Determining the shape of the data set

combined_data.shape

(2879, 18)

In [15]:
# Determining null values

combined_data.isna().any()

Company_Brand    True
Founded          True
HeadQuarter      True
Sector           True
What_it_does     True
Founders         True
Investor         True
Amount           True
Stage            True
column10         True
Company/Brand    True
What it does     True
Amount($)        True
Company Name     True
Industry         True
Round/Series     True
Location         True
About Company    True
dtype: bool

In [16]:
# Determining null values

combined_data.isna().sum()

Company_Brand     615
Founded           769
HeadQuarter       640
Sector            544
What_it_does      615
Founders          545
Investor          626
Amount            346
Stage            1464
column10         2877
Company/Brand    2790
What it does     2790
Amount($)        2790
Company Name     2353
Industry         2353
Round/Series     2353
Location         2353
About Company    2353
dtype: int64

In [17]:
#Assessing columns in all the data sets

combined_data.columns

Index(['Company_Brand', 'Founded', 'HeadQuarter', 'Sector', 'What_it_does',
       'Founders', 'Investor', 'Amount', 'Stage', 'column10', 'Company/Brand',
       'What it does', 'Amount($)', 'Company Name', 'Industry', 'Round/Series',
       'Location', 'About Company'],
      dtype='object')

In [18]:
#Gaining an overvew of the data

combined_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2879 entries, 0 to 2878
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company_Brand  2264 non-null   object
 1   Founded        2110 non-null   float64
 2   HeadQuarter    2239 non-null   object
 3   Sector         2335 non-null   object
 4   What_it_does   2264 non-null   object
 5   Founders       2334 non-null   object
 6   Investor       2253 non-null   object
 7   Amount         2533 non-null   object
 8   Stage          1415 non-null   object
 9   column10       2 non-null      object
 10  Company/Brand  89 non-null     object
 11  What it does   89 non-null     object
 12  Amount($)      89 non-null     object
 13  Company Name   526 non-null    object
 14  Industry       526 non-null    object
 15  Round/Series   526 non-null    object
 16  Location       526 non-null    object
 17  About Company  526 non-null    object
dtypes: float64(1), object(17)
memory usage: 405.0+ KB

In [19]:
# Determining the datatypes

combined_data.dtypes

Company_Brand     object
Founded          float64
HeadQuarter       object
Sector            object
What_it_does      object
Founders          object
Investor          object
Amount            object
Stage             object
column10          object
Company/Brand     object
What it does      object
Amount($)         object
Company Name      object
Industry          object
Round/Series      object
Location          object
About Company     object
dtype: object

In [20]:
# Getting an overview of the data

combined_data.describe().T

# This gave us a description of the year founded only since it is the only float datatype in the dataset

          count         mean       std     min     25%     50%     75%     max
Founded  2110.0  2016.079621  4.368006  1963.0  2015.0  2017.0  2019.0  2021.0

In [21]:
# Getting an overview of the Amount column to try and understand why it isn't grouped as a float

combined_data.loc[:, 'Amount']

0                            $1,200,000
1                          $120,000,000
2                           $30,000,000
3                           $51,000,000
4                            $2,000,000
5                          $188,000,000
6                              $200,000
7                           Undisclosed
8                           Undisclosed
9                            $1,000,000
10                           $3,000,000
11                             $100,000
12                             $700,000
13                           $2,000,000
14                           $9,000,000
15                          $40,000,000
16                          $49,000,000
17                             $400,000
18                             $300,000
19                          $25,000,000
20                         $160,000,000
21                          Undisclosed
22                             $150,000
23                           $1,800,000
24                           $5,000,000
25                             $850,000
26                           $3,000,000
27                          $53,000,000
28                           $2,000,000
29                             $500,000
30                           $1,100,000
31                           $6,000,000
32                             $800,000
33                             $500,000
34                           $1,000,000
35                          $10,000,000
36                             $500,000
37                             $200,000
38                           $6,000,000
39                          Undisclosed
40                          $21,000,000
41                             $100,000
42                           $1,000,000
43                           $7,500,000
44                             $100,000
45                           $1,000,000
46                          $26,000,000
47                           $1,000,000
48                           $7,400,000
49                           $2,000,000
50                           $1,500,000
51                           $3,000,000
52                             $600,000
53                         $800,000,000
54                          Undisclosed
55                          $17,000,000
56                           $3,500,000
57                          $15,000,000
58                         $215,000,000
59                           $2,500,000
60                         $350,000,000
61                           $2,000,000
62                           $5,500,000
63                             $600,000
64                          Undisclosed
65                          $83,000,000
66                          $26,000,000
67                          Undisclosed
68                         $110,000,000
69                           $3,000,000
70                         $500,000,000
71                           $1,000,000
72                          $65,000,000
73                     $150,000,000,000
74                           $6,000,000
75                             $700,000
76                          $10,000,000
77                             $700,000
78                         $300,000,000
79                           $2,200,000
80                          $35,000,000
81                         $140,000,000
82                             $200,000
83                           $4,000,000
84                          $13,000,000
85                           $1,100,000
86                                 None
87                         $Undisclosed
88                             $2000000
89                             $2000000
90                              $800000
91                             $6000000
92                             $2500000
93                             $9500000
94                            $13000000
95                             $5000000
96                             $8000000
97                             $1000000
98                             Upsparks
99                         $Undisclosed
100                             $200000
101                           $12000000
102                            $1500000
103                            $2000000
104                            $1700000
105                            $5500000
106                            $1000000
107                           $13000000
108                            $5000000
109                            $8000000
110                            $1000000
111                            Upsparks
112                        $Undisclosed
113                             $200000
114                           $12000000
115                            $1500000
116                            $2000000
117                            $1700000
118                            $5500000
119                            $1000000
120                             $400000
121                          $150000000
122                            $4000000
123                        $Undisclosed
124                          $100000000
125                            $6000000
126                            $1000000
127                        $Undisclosed
128                             $500000
129                            $2000000
130                        $Undisclosed
131                            $5500000
132                        $Undisclosed
133                           $15000000
134                            $2000000
135                             $500000
136                            $1000000
137                           $10000000
138                           $40000000
139                           $10000000
140                        $Undisclosed
141                          $225000000
142                            $6700000
143                            $1300000
144                           $20000000
145                             $250000
146                        $Undisclosed
147                           $21000000
148                             $400000
149                            $1200000
150                            $5000000
151                           $52000000
152                             $400000
153                            $3800000
154                           $17500000
155                           $42000000
156                            $6000000
157                            $3800000
158                            $2000000
159                            $2300000
160                            $5000000
161                           $20000000
162                            $1000000
163                            $7000000
164                           $30000000
165                            $1000000
166                          $450000000
167                        $Undisclosed
168                           $28000000
169                             $300000
170                            $3500000
171                        $Undisclosed
172                            $8500000
173                           $25000000
174                             $500000
175                            $1700000
176                            $3500000
177                           $25000000
178                             $400000
179                            $1000000
180                           $12000000
181                          $225000000
182                            $3000000
183                           $37000000
184                            $2000000
185                            $2000000
186                          $370000000
187                             $700000
188                            $5000000
189                           $16000000
190                            $2000000
191                             $500000
192                        $Undisclosed
193                        $Undisclosed
194                             $200000
195                           $10000000
196                            $2000000
197                             $100000
198                           $44000000
199                            $1000000
200                             $500000
201                           $20000000
202                           $10000000
203                            $1700000
204                            $3500000
205                             $300000
206                           $20000000
207                        $Undisclosed
208                             $770000
209                            $1200000
210                        $Undisclosed
211                          $125000000
212                           $35000000
213                           $40000000
214                           $40000000
215                           $50000000
216                            $4900000
217                          $145000000
218                           $22000000
219                           $10000000
220                           $13000000
221                           $10000000
222                           $10000000
223                           $70000000
224                          $100000000
225                            $6700000
226                           $30000000
227                            $7000000
228                            $5000000
229                            $6600000
230                           $32000000
231                          $150000000
232                           $24000000
233                             $700000
234                        $Undisclosed
235                             $200000
236                            $1500000
237                            $1300000
238                            $1000000
239                             $725000
240                             $500000
241                             $461000
242                            Series C
243                            $6600000
244                           $32000000
245                          $150000000
246                           $24000000
247                             $700000
248                        $Undisclosed
249                             $200000
250                            $1500000
251                            $1300000
252                            $1000000
253                             $725000
254                             $500000
255                             $461000
256                            Series C
257                                Seed
258                           $96000000
259                            $5000000
260                           $70000000
261                            $5000000
262                            $4000000
263                           $32000000
264                           $60000000
265                            $7000000
266                           $20000000
267                          $500000000
268                          $266000000
269                            $4500000
270                            $1200000
271                            $4000000
272                             $300000
273                             $200000
274                            $9500000
275                            $1200000
276                          $325000000
277                          $100000000
278                            $6500000
279                            $4000000
280                            $1600000
281                             $150000
282                             $400000
283                             $225000
284                            $5000000
285                          $100000000
286                           $10000000
287                           $85000000
288                           $40000000
289                             $200000
290                             $235000
291                             $260000
292                            $7000000
293                           $30000000
294                            $2900000
295                           $12000000
296                           $53000000
297                            $3500000
298                             $700000
299                            $3000000
300                            $1000000
301                        $Undisclosed
302                            $3000000
303                            $1100000
304                        $Undisclosed
305                        $Undisclosed
306                           $86000000
307                             $130000
308                            $$100,00
309                          $111000000
310                           $37000000
311                            $6000000
312                             $265000
313                            $1000000
314                           $76000000
315                         $30,000,000
316                         Undisclosed
317                        $100,000,000
318                            $200,000
319                         Undisclosed
320                          $2,000,000
321                         Undisclosed
322                          $4,000,000
323                         $75,000,000
324                          $1,000,000
325                         Undisclosed
326                          $3,800,000
327                          $1,500,000
328                            $800,000
329                         $15,000,000
330                          $3,000,000
331                          $2,000,000
332                          $1,000,000
333                        $100,000,000
334                         Undisclosed
335                         $12,000,000
336                         Undisclosed
337                            $100,000
338                          $1,600,000
339                        $100,000,000
340                            $260,000
341                          $2,000,000
342                            $300,000
343                         $30,000,000
344                            $400,000
345                         Undisclosed
346                      $1,000,000,000
347                            $200,000
348                            $400,000
349                          $5,000,000
350                         $15,000,000
351                          $1,000,000
352                         $10,000,000
353                          $1,000,000
354                          $2,000,000
355                         $10,000,000
356                            $200,000
357                          $1,000,000
358                            $600,000
359                         $10,000,000
360                          $6,000,000
361                         $18,000,000
362                          $2,200,000
363                            $150,000
364                         $40,000,000
365                        $120,000,000
366                            $500,000
367                         Undisclosed
368                         $20,000,000
369                            $350,000
370                          $1,000,000
371                            $200,000
372                         $95,000,000
373                          $4,100,000
374                          $5,200,000
375                         $10,000,000
376                         Undisclosed
377                          $5,000,000
378                          $4,000,000
379                         Undisclosed
380                          $8,000,000
381                          $1,400,000
382                          $1,500,000
383                         Undisclosed
384                         Undisclosed
385                         $10,000,000
386                         Undisclosed
387                          $1,000,000
388                          $1,000,000
389                            $300,000
390                          $1,000,000
391                          $9,000,000
392                          $3,000,000
393                         Undisclosed
394                          $5,000,000
395                          $2,000,000
396                          $6,000,000
397                         $40,000,000
398                          $2,000,000
399                          $1,000,000
400                          $2,600,000
401                          $6,000,000
402                          $1,600,000
403                          $2,000,000
404                            $900,000
405                            $250,000
406                         Undisclosed
407                         $10,000,000
408                         $16,000,000
409                          $2,500,000
410                          $7,000,000
411                         $15,000,000
412                         $30,000,000
413                         $10,000,000
414                          $1,500,000
415                          $1,000,000
416                          $1,000,000
417                          $2,000,000
418                            $300,000
419                          $1,500,000
420                          $3,000,000
421                         $15,000,000
422                         $11,000,000
423                          $6,000,000
424                          $1,000,000
425                          $7,000,000
426                        $280,000,000
427                         $50,000,000
428                          $3,000,000
429                         Undisclosed
430                         Undisclosed
431                            $200,000
432                          $1,800,000
433                          $5,000,000
434                         $14,300,000
435                          $4,000,000
436                         $10,000,000
437                         Undisclosed
438                            $300,000
439                            $500,000
440                          $4,000,000
441                         $81,000,000
442                          $1,000,000
443                          $1,300,000
444                        $100,000,000
445                          $2,000,000
446                          $5,000,000
447                            $300,000
448                          $8,200,000
449                         $20,000,000
450                            $200,000
451                          $7,000,000
452                         Undisclosed
453                          $4,000,000
454                            $100,000
455                            $500,000
456                         $70,000,000
457                            $720,000
458                          $3,000,000
459                            $3000000
460                           $15000000
461                             $600000
462                           $10000000
463                            $9000000
464                            $1000000
465                           $10000000
466                            $5000000
467                            $1800000
468                            $6000000
469                             $300000
470                            $1500000
471                            $2000000
472                            $1000000
473                            $4000000
474                           $40000000
475                            $1600000
476                            $2000000
477                            $2000000
478                            $5000000
479                             $300000
480                             $330000
481                            $1000000
482                           $53000000
483                            $6000000
484                             $800000
485                        $undisclosed
486                          $200000000
487                            $1000000
488                            $2000000
489                           $50000000
490                           $36000000
491                        $undisclosed
492                             $300000
493                             $200000
494                            $1000000
495                            $5000000
496                           $67000000
497                            $2000000
498                        $undisclosed
499                            $2500000

In [22]:
# Removing characters from the Amount column

combined_data['Amount'] = combined_data['Amount'].str.replace('[$₹]', '', regex=True)
combined_data['Amount'] = combined_data['Amount'].str.replace(',', '')

combined_data['Amount']

0                              1200000
1                            120000000
2                             30000000
3                             51000000
4                              2000000
5                            188000000
6                               200000
7                          Undisclosed
8                          Undisclosed
9                              1000000
10                             3000000
11                              100000
12                              700000
13                             2000000
14                             9000000
15                            40000000
16                            49000000
17                              400000
18                              300000
19                            25000000
20                           160000000
21                         Undisclosed
22                              150000
23                             1800000
24                             5000000
25                              850000
26                             3000000
27                            53000000
28                             2000000
29                              500000
30                             1100000
31                             6000000
32                              800000
33                              500000
34                             1000000
35                            10000000
36                              500000
37                              200000
38                             6000000
39                         Undisclosed
40                            21000000
41                              100000
42                             1000000
43                             7500000
44                              100000
45                             1000000
46                            26000000
47                             1000000
48                             7400000
49                             2000000
50                             1500000
51                             3000000
52                              600000
53                           800000000
54                         Undisclosed
55                            17000000
56                             3500000
57                            15000000
58                           215000000
59                             2500000
60                           350000000
61                             2000000
62                             5500000
63                              600000
64                         Undisclosed
65                            83000000
66                            26000000
67                         Undisclosed
68                           110000000
69                             3000000
70                           500000000
71                             1000000
72                            65000000
73                        150000000000
74                             6000000
75                              700000
76                            10000000
77                              700000
78                           300000000
79                             2200000
80                            35000000
81                           140000000
82                              200000
83                             4000000
84                            13000000
85                             1100000
86                                None
87                         Undisclosed
88                             2000000
89                             2000000
90                              800000
91                             6000000
92                             2500000
93                             9500000
94                            13000000
95                             5000000
96                             8000000
97                             1000000
98                            Upsparks
99                         Undisclosed
100                             200000
101                           12000000
102                            1500000
103                            2000000
104                            1700000
105                            5500000
106                            1000000
107                           13000000
108                            5000000
109                            8000000
110                            1000000
111                           Upsparks
112                        Undisclosed
113                             200000
114                           12000000
115                            1500000
116                            2000000
117                            1700000
118                            5500000
119                            1000000
120                             400000
121                          150000000
122                            4000000
123                        Undisclosed
124                          100000000
125                            6000000
126                            1000000
127                        Undisclosed
128                             500000
129                            2000000
130                        Undisclosed
131                            5500000
132                        Undisclosed
133                           15000000
134                            2000000
135                             500000
136                            1000000
137                           10000000
138                           40000000
139                           10000000
140                        Undisclosed
141                          225000000
142                            6700000
143                            1300000
144                           20000000
145                             250000
146                        Undisclosed
147                           21000000
148                             400000
149                            1200000
150                            5000000
151                           52000000
152                             400000
153                            3800000
154                           17500000
155                           42000000
156                            6000000
157                            3800000
158                            2000000
159                            2300000
160                            5000000
161                           20000000
162                            1000000
163                            7000000
164                           30000000
165                            1000000
166                          450000000
167                        Undisclosed
168                           28000000
169                             300000
170                            3500000
171                        Undisclosed
172                            8500000
173                           25000000
174                             500000
175                            1700000
176                            3500000
177                           25000000
178                             400000
179                            1000000
180                           12000000
181                          225000000
182                            3000000
183                           37000000
184                            2000000
185                            2000000
186                          370000000
187                             700000
188                            5000000
189                           16000000
190                            2000000
191                             500000
192                        Undisclosed
193                        Undisclosed
194                             200000
195                           10000000
196                            2000000
197                             100000
198                           44000000
199                            1000000
200                             500000
201                           20000000
202                           10000000
203                            1700000
204                            3500000
205                             300000
206                           20000000
207                        Undisclosed
208                             770000
209                            1200000
210                        Undisclosed
211                          125000000
212                           35000000
213                           40000000
214                           40000000
215                           50000000
216                            4900000
217                          145000000
218                           22000000
219                           10000000
220                           13000000
221                           10000000
222                           10000000
223                           70000000
224                          100000000
225                            6700000
226                           30000000
227                            7000000
228                            5000000
229                            6600000
230                           32000000
231                          150000000
232                           24000000
233                             700000
234                        Undisclosed
235                             200000
236                            1500000
237                            1300000
238                            1000000
239                             725000
240                             500000
241                             461000
242                           Series C
243                            6600000
244                           32000000
245                          150000000
246                           24000000
247                             700000
248                        Undisclosed
249                             200000
250                            1500000
251                            1300000
252                            1000000
253                             725000
254                             500000
255                             461000
256                           Series C
257                               Seed
258                           96000000
259                            5000000
260                           70000000
261                            5000000
262                            4000000
263                           32000000
264                           60000000
265                            7000000
266                           20000000
267                          500000000
268                          266000000
269                            4500000
270                            1200000
271                            4000000
272                             300000
273                             200000
274                            9500000
275                            1200000
276                          325000000
277                          100000000
278                            6500000
279                            4000000
280                            1600000
281                             150000
282                             400000
283                             225000
284                            5000000
285                          100000000
286                           10000000
287                           85000000
288                           40000000
289                             200000
290                             235000
291                             260000
292                            7000000
293                           30000000
294                            2900000
295                           12000000
296                           53000000
297                            3500000
298                             700000
299                            3000000
300                            1000000
301                        Undisclosed
302                            3000000
303                            1100000
304                        Undisclosed
305                        Undisclosed
306                           86000000
307                             130000
308                              10000
309                          111000000
310                           37000000
311                            6000000
312                             265000
313                            1000000
314                           76000000
315                           30000000
316                        Undisclosed
317                          100000000
318                             200000
319                        Undisclosed
320                            2000000
321                        Undisclosed
322                            4000000
323                           75000000
324                            1000000
325                        Undisclosed
326                            3800000
327                            1500000
328                             800000
329                           15000000
330                            3000000
331                            2000000
332                            1000000
333                          100000000
334                        Undisclosed
335                           12000000
336                        Undisclosed
337                             100000
338                            1600000
339                          100000000
340                             260000
341                            2000000
342                             300000
343                           30000000
344                             400000
345                        Undisclosed
346                         1000000000
347                             200000
348                             400000
349                            5000000
350                           15000000
351                            1000000
352                           10000000
353                            1000000
354                            2000000
355                           10000000
356                             200000
357                            1000000
358                             600000
359                           10000000
360                            6000000
361                           18000000
362                            2200000
363                             150000
364                           40000000
365                          120000000
366                             500000
367                        Undisclosed
368                           20000000
369                             350000
370                            1000000
371                             200000
372                           95000000
373                            4100000
374                            5200000
375                           10000000
376                        Undisclosed
377                            5000000
378                            4000000
379                        Undisclosed
380                            8000000
381                            1400000
382                            1500000
383                        Undisclosed
384                        Undisclosed
385                           10000000
386                        Undisclosed
387                            1000000
388                            1000000
389                             300000
390                            1000000
391                            9000000
392                            3000000
393                        Undisclosed
394                            5000000
395                            2000000
396                            6000000
397                           40000000
398                            2000000
399                            1000000
400                            2600000
401                            6000000
402                            1600000
403                            2000000
404                             900000
405                             250000
406                        Undisclosed
407                           10000000
408                           16000000
409                            2500000
410                            7000000
411                           15000000
412                           30000000
413                           10000000
414                            1500000
415                            1000000
416                            1000000
417                            2000000
418                             300000
419                            1500000
420                            3000000
421                           15000000
422                           11000000
423                            6000000
424                            1000000
425                            7000000
426                          280000000
427                           50000000
428                            3000000
429                        Undisclosed
430                        Undisclosed
431                             200000
432                            1800000
433                            5000000
434                           14300000
435                            4000000
436                           10000000
437                        Undisclosed
438                             300000
439                             500000
440                            4000000
441                           81000000
442                            1000000
443                            1300000
444                          100000000
445                            2000000
446                            5000000
447                             300000
448                            8200000
449                           20000000
450                             200000
451                            7000000
452                        Undisclosed
453                            4000000
454                             100000
455                             500000
456                           70000000
457                             720000
458                            3000000
459                            3000000
460                           15000000
461                             600000
462                           10000000
463                            9000000
464                            1000000
465                           10000000
466                            5000000
467                            1800000
468                            6000000
469                             300000
470                            1500000
471                            2000000
472                            1000000
473                            4000000
474                           40000000
475                            1600000
476                            2000000
477                            2000000
478                            5000000
479                             300000
480                             330000
481                            1000000
482                           53000000
483                            6000000
484                             800000
485                        undisclosed
486                          200000000
487                            1000000
488                            2000000
489                           50000000
490                           36000000
491                        undisclosed
492                             300000
493                             200000
494                            1000000
495                            5000000
496                           67000000
497                            2000000
498                        undisclosed
499                            2500000
500                        undisclosed
501                        undisclosed
502                            5000000
503                           12000000
504                           10200000
505                          220000000
506                            4500000
507                             200000
508                            1000000
509                           25000000
510                          150000000
511                          108000000

In [24]:
# To determine how many labels of 'undisclosed' figures are in the column

# Using value_counts to get the count of 'undisclosed'
undisclosed_count = combined_data['Amount'].value_counts()
undisclosed_count

Amount
—                                 148
Undisclosed                       116
1000000                           112
2000000                            75
3000000                            54
5000000                            53
500000                             50
10000000                           49
200000                             42
4000000                            37
300000                             31
30000000                           29
20000000                           28
50000000                           28
6000000                            27
1500000                            27
400000                             27
100000000                          22
100000                             22
undisclosed                        22
15000000                           21
40000000                           21
7000000                            18
1200000                            16
600000                             16
700000                             16
12000000                           14
8000000                            12
150000                             12
35000000                           12
800000                             11
1100000                            11
1300000                            11
3500000                            11
2500000                            11
25000000                           10
11000000                           10
1800000                             9
75000000                            9
70000000                            9
250000                              9
1600000                             8
4500000                             8
150000000                           8
1700000                             7
5500000                             7
250000000                           7
200000000                           7
9000000                             7
60000000                            7
140000000                           6
2200000                             6
24000000                            6
45000000                            6
13000000                            6
900000                              5
16000000                            5
1400000                             5
65000000                            5
2300000                             4
12500000                            4
3800000                             4
26000000                            4
600000000                           4
120000000                           4
125000000                           4
17000000                            4
1000000000                          4
32000000                            4
22000000                            3
125000                              3
64000000                            3
6500000                             3
53000000                            3
320000                              3
4200000                             3
210000000                           3
2600000                             3
2000000000                          3
21000000                            3
5200000                             3
135000000                           3
400000000                           3
225000000                           3
9500000                             3
120000                              3
28000000                            3
280000000                           2
90000000                            2
750000                              2
23000000                            2
3200000                             2
78000000                            2
4300000                             2
36000000                            2
220000000                           2
72000000                            2
                                    2
550000000                           2
260000000                           2
330000                              2
1250000                             2
370000                              2
240000000                           2
20000                               2
48000000                            2
550000                              2
3600000                             2
1900000                             2
140000                              2
2500000000                          2
3300000                             2
2700000                             2
50000                               2
340000                              2
650000000                           2
6300000                             2
14000000                            2
260000                              2
4100000                             2
Seed                                2
461000                              2
725000                              2
6600000                             2
80000000                            2
44000000                            2
95000000                            2
37000000                            2
450000000                           2
42000000                            2
52000000                            2
6700000                             2
Upsparks                            2
300000000                           2
500000000                           2
350000000                           2
800000000                           2
7500000                             2
Series C                            2
650000                              2
10000                               2
350000                              2
130000                              2
76000000                            2
18000000                            2
99230000                            1
143145                              1
742000000                           1
3530000                             1
5600000                             1
3980000                             1
342000000                           1
1410000000                          1
41900000                            1
28500000                            1
2400000                             1
340000000                           1
40000                               1
34000000                            1
3240000                             1
580000000                           1
365000000                           1
60000                               1
26400000                            1
8750000                             1
264000000                           1
13400000                            1
104000000                           1
1130000000                          1
810000000                           1
2800000                             1
1400000000                          1
14900000                            1
3700000                             1
15392000000                         1
20000000000                         1
540000000                           1
1450000                             1
4000000000                          1
185000000                           1
175000                              1
70000                               1
103000000                           1
19200000                            1
180000                              1
2200000000                          1
16600000                            1
33000000                            1
140200000                           1
34900000                            1
165000000                           1
2029600000                          1
13200000                            1
22500000                            1
510000000                           1
37680000                            1
364846                              1
6830000                             1
17200000                            1
1041000                             1
5200000000                          1
102500000                           1
1600000000                          1
1760000                             1
1540000000                          1
730000000                           1
15000                               1
Pre-series A                        1
55000000                            1
266000000                           1
225000                              1
85000000                            1
235000                              1
2900000                             1
86000000                            1
111000000                           1
265000                              1
14300000                            1
81000000                            1
8200000                             1
720000                              1
67000000                            1
10200000                            1
108000000                           1
450000                              1
325000000                           1
96000000                            1
ah! Ventures                        1
145000000                           1
51000000                            1
188000000                           1
49000000                            1
160000000                           1
850000                              1
7400000                             1
215000000                           1
83000000                            1
110000000                           1
150000000000                        1
17500000                            1
8500000                             1
370000000                           1
770000                              1
4900000                             1
660000000                           1
ITO Angel Network LetsVenture       1
6200000                             1
155000                              1
840000000                           1
248000000                           1
570000                              1
4700000                             1
175000000                           1
19000000                            1
810000                              1
5700000                             1
6750000                             1
5400000                             1
115000000                           1
255000000                           1
570000000                           1
31000000                            1
540000                              1
2100000                             1
92000000                            1
192000000                           1
43000000                            1
41000000                            1
144000000                           1
270000000                           1
4800000                             1
38000000                            1
620000                              1
JITO Angel Network LetsVenture      1
27000000                            1
234000000                           1
460000000                           1
13500000                            1
5100000                             1
195000000                           1
7300000                             1
16500000                            1
7500                                1
Name: count, dtype: int64

The above code helps us realize that not only are there 'Undisclosed' values but also 'undisclosed' values, the difference is in the capitalization. Also it is good to note that the count of this values are roughly 138.

In [25]:
# Determining unique values

combined_data.nunique()

Company_Brand    1745
Founded            34
HeadQuarter       123
Sector            502
What_it_does     2112
Founders         1980
Investor         1777
Amount            283
Stage              62
column10            2
Company/Brand      87
What it does       88
Amount($)          50
Company Name      525
Industry          405
Round/Series       21
Location           50
About Company     524
dtype: int64

In [26]:
# Checking for duplicates

combined_data.loc[combined_data.duplicated()].head()

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,column10,Company/Brand,What it does,Amount($),Company Name,Industry,Round/Series,Location,About Company
107,Curefoods,2020.0,Bangalore,Food & Beverages,Healthy & nutritious foods and cold pressed ju...,Ankit Nagori,"Iron Pillar, Nordstar, Binny Bansal",13000000,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Bewakoof,2012.0,Mumbai,Apparel & Fashion,Bewakoof is a lifestyle fashion brand that mak...,Prabhkiran Singh,InvestCorp,8000000,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,FanPlay,2020.0,Computer Games,Computer Games,A real money game app specializing in trivia g...,YC W21,"Pritesh Kumar, Bharat Gupta",Upsparks,$1200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,Advantage Club,2014.0,Mumbai,HRTech,Advantage Club is India's largest employee eng...,"Sourabh Deorah, Smiti Bhatt Deorah","Y Combinator, Broom Ventures, Kunal Shah",1700000,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,Ruptok,2020.0,New Delhi,FinTech,Ruptok fintech Pvt. Ltd. is an online gold loa...,Ankur Gupta,Eclear Leasing,1000000,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# Narrowing it down to a column

combined_data.loc[combined_data.duplicated(subset='Company_Brand')].head(5)

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,column10,Company/Brand,What it does,Amount($),Company Name,Industry,Round/Series,Location,About Company
80,Uable,2020.0,Bangalore,EdTech,Uable are on a bold mission to redefine the fu...,Saurabh Saxena,"JAFCO Asia, Chiratae Ventures",35000000,Pre-series A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,Curefoods,2020.0,Bangalore,Food & Beverages,Healthy & nutritious foods and cold pressed ju...,Ankit Nagori,"Iron Pillar, Nordstar, Binny Bansal",13000000,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,TartanSense,2015.0,Bangalore,Information Technology,TartanSense unlocks value for small farm holde...,Jaisimha Rao,"FMC, Omnivore, Blume Ventures",5000000,Series A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Bewakoof,2012.0,Mumbai,Apparel & Fashion,Bewakoof is a lifestyle fashion brand that mak...,Prabhkiran Singh,InvestCorp,8000000,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,Kirana247,2018.0,New Delhi,Logistics & Supply Chain,An on-demand FMCG supply chain company leverag...,"Tarun Jiwarajka, Pankhuri Jiwarajka",None,1000000,Pre-series A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
# Checking an example duplicate

combined_data.query("Company_Brand == 'Kirana247'")

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,column10,Company/Brand,What it does,Amount($),Company Name,Industry,Round/Series,Location,About Company
97,Kirana247,2018.0,New Delhi,Logistics & Supply Chain,An on-demand FMCG supply chain company leverag...,"Tarun Jiwarajka, Pankhuri Jiwarajka",None,1000000,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,Kirana247,2018.0,New Delhi,Logistics & Supply Chain,An on-demand FMCG supply chain company leverag...,"Tarun Jiwarajka, Pankhuri Jiwarajka",None,1000000,Pre-series A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
combined_data.columns

Index(['Company_Brand', 'Founded', 'HeadQuarter', 'Sector', 'What_it_does',
       'Founders', 'Investor', 'Amount', 'Stage', 'column10', 'Company/Brand',
       'What it does', 'Amount($)', 'Company Name', 'Industry', 'Round/Series',
       'Location', 'About Company'],
      dtype='object')


# **Data Cleaning**

In [30]:
# Concatenate all datasets

combined_data = pd.concat([data_021, data_020, data_019, data_018], ignore_index=True)

In [31]:
combined_data.columns

Index(['Company_Brand', 'Founded', 'HeadQuarter', 'Sector', 'What_it_does',
       'Founders', 'Investor', 'Amount', 'Stage', 'column10', 'Company/Brand',
       'What it does', 'Amount($)', 'Company Name', 'Industry', 'Round/Series',
       'Location', 'About Company'],
      dtype='object')

In [32]:
# Dropping irrelevant columns

combined_data.drop('column10', axis =1, inplace = True)

In [33]:
combined_data.columns

Index(['Company_Brand', 'Founded', 'HeadQuarter', 'Sector', 'What_it_does',
       'Founders', 'Investor', 'Amount', 'Stage', 'Company/Brand',
       'What it does', 'Amount($)', 'Company Name', 'Industry', 'Round/Series',
       'Location', 'About Company'],
      dtype='object')

In [34]:
combined_data.tail()

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,Company/Brand,What it does,Amount($),Company Name,Industry,Round/Series,Location,About Company
2874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,225000000,NaN,NaN,NaN,NaN,Udaan,"B2B, Business Development, Internet, Marketplace",Series C,"Bangalore, Karnataka, India","Udaan is a B2B trade platform, designed specif..."
2875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,—,NaN,NaN,NaN,NaN,Happyeasygo Group,"Tourism, Travel",Series A,"Haryana, Haryana, India",HappyEasyGo is an online travel domain.
2876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7500,NaN,NaN,NaN,NaN,Mombay,"Food and Beverage, Food Delivery, Internet",Seed,"Mumbai, Maharashtra, India",Mombay is a unique opportunity for housewives ...
2877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"₹35,000,000",NaN,NaN,NaN,NaN,Droni Tech,Information Technology,Seed,"Mumbai, Maharashtra, India",Droni Tech manufacture UAVs and develop softwa...
2878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35000000,NaN,NaN,NaN,NaN,Netmeds,"Biotechnology, Health Care, Pharmaceutical",Series C,"Chennai, Tamil Nadu, India",Welcome to India's most convenient pharmacy!

In [35]:
# Consolidate names of the company into a single column

combined_data['Company_Name'] = combined_data['Company_Brand'].combine_first(combined_data['Company/Brand']).combine_first(combined_data['Company Name'])
combined_data.tail()

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,Company/Brand,What it does,Amount($),Company Name,Industry,Round/Series,Location,About Company,Company_Name
2874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,225000000,NaN,NaN,NaN,NaN,Udaan,"B2B, Business Development, Internet, Marketplace",Series C,"Bangalore, Karnataka, India","Udaan is a B2B trade platform, designed specif...",Udaan
2875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,—,NaN,NaN,NaN,NaN,Happyeasygo Group,"Tourism, Travel",Series A,"Haryana, Haryana, India",HappyEasyGo is an online travel domain.,Happyeasygo Group
2876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7500,NaN,NaN,NaN,NaN,Mombay,"Food and Beverage, Food Delivery, Internet",Seed,"Mumbai, Maharashtra, India",Mombay is a unique opportunity for housewives ...,Mombay
2877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"₹35,000,000",NaN,NaN,NaN,NaN,Droni Tech,Information Technology,Seed,"Mumbai, Maharashtra, India",Droni Tech manufacture UAVs and develop softwa...,Droni Tech
2878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35000000,NaN,NaN,NaN,NaN,Netmeds,"Biotechnology, Health Care, Pharmaceutical",Series C,"Chennai, Tamil Nadu, India",Welcome to India's most convenient pharmacy!,Netmeds

In [36]:
combined_data.columns

Index(['Company_Brand', 'Founded', 'HeadQuarter', 'Sector', 'What_it_does',
       'Founders', 'Investor', 'Amount', 'Stage', 'Company/Brand',
       'What it does', 'Amount($)', 'Company Name', 'Industry', 'Round/Series',
       'Location', 'About Company', 'Company_Name'],
      dtype='object')

We use the combine_first() method to merge 'Company Name' and 'Company_Brand' columns into a new 'Company_Name' column. This method fills missing values in the 'Company_Name' column with corresponding non-missing values from the 'Company_Brand' column.

In [37]:
# Drop the original company column names
# Drop the original 'Company Name' and 'Company_Brand' columns using the drop() method.

combined_data.drop(['Company Name', 'Company_Brand', 'Company/Brand'], axis=1, inplace=True, errors='ignore')
combined_data.tail()

,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,What it does,Amount($),Industry,Round/Series,Location,About Company,Company_Name
2874,NaN,NaN,NaN,NaN,NaN,NaN,225000000,NaN,NaN,NaN,"B2B, Business Development, Internet, Marketplace",Series C,"Bangalore, Karnataka, India","Udaan is a B2B trade platform, designed specif...",Udaan
2875,NaN,NaN,NaN,NaN,NaN,NaN,—,NaN,NaN,NaN,"Tourism, Travel",Series A,"Haryana, Haryana, India",HappyEasyGo is an online travel domain.,Happyeasygo Group
2876,NaN,NaN,NaN,NaN,NaN,NaN,7500,NaN,NaN,NaN,"Food and Beverage, Food Delivery, Internet",Seed,"Mumbai, Maharashtra, India",Mombay is a unique opportunity for housewives ...,Mombay
2877,NaN,NaN,NaN,NaN,NaN,NaN,"₹35,000,000",NaN,NaN,NaN,Information Technology,Seed,"Mumbai, Maharashtra, India",Droni Tech manufacture UAVs and develop softwa...,Droni Tech
2878,NaN,NaN,NaN,NaN,NaN,NaN,35000000,NaN,NaN,NaN,"Biotechnology, Health Care, Pharmaceutical",Series C,"Chennai, Tamil Nadu, India",Welcome to India's most convenient pharmacy!,Netmeds

In [38]:
combined_data.columns

Index(['Founded', 'HeadQuarter', 'Sector', 'What_it_does', 'Founders',
       'Investor', 'Amount', 'Stage', 'What it does', 'Amount($)', 'Industry',
       'Round/Series', 'Location', 'About Company', 'Company_Name'],
      dtype='object')

Trying to apply the same combine.first method to the amounts column since they are two instead of dropping the 'Amount($)' column as it has a few significant values

In [39]:
# This 'Amount' column seems to have a ton of figures

combined_data['Amount']

0                            $1,200,000
1                          $120,000,000
2                           $30,000,000
3                           $51,000,000
4                            $2,000,000
5                          $188,000,000
6                              $200,000
7                           Undisclosed
8                           Undisclosed
9                            $1,000,000
10                           $3,000,000
11                             $100,000
12                             $700,000
13                           $2,000,000
14                           $9,000,000
15                          $40,000,000
16                          $49,000,000
17                             $400,000
18                             $300,000
19                          $25,000,000
20                         $160,000,000
21                          Undisclosed
22                             $150,000
23                           $1,800,000
24                           $5,000,000
25                             $850,000
26                           $3,000,000
27                          $53,000,000
28                           $2,000,000
29                             $500,000
30                           $1,100,000
31                           $6,000,000
32                             $800,000
33                             $500,000
34                           $1,000,000
35                          $10,000,000
36                             $500,000
37                             $200,000
38                           $6,000,000
39                          Undisclosed
40                          $21,000,000
41                             $100,000
42                           $1,000,000
43                           $7,500,000
44                             $100,000
45                           $1,000,000
46                          $26,000,000
47                           $1,000,000
48                           $7,400,000
49                           $2,000,000
50                           $1,500,000
51                           $3,000,000
52                             $600,000
53                         $800,000,000
54                          Undisclosed
55                          $17,000,000
56                           $3,500,000
57                          $15,000,000
58                         $215,000,000
59                           $2,500,000
60                         $350,000,000
61                           $2,000,000
62                           $5,500,000
63                             $600,000
64                          Undisclosed
65                          $83,000,000
66                          $26,000,000
67                          Undisclosed
68                         $110,000,000
69                           $3,000,000
70                         $500,000,000
71                           $1,000,000
72                          $65,000,000
73                     $150,000,000,000
74                           $6,000,000
75                             $700,000
76                          $10,000,000
77                             $700,000
78                         $300,000,000
79                           $2,200,000
80                          $35,000,000
81                         $140,000,000
82                             $200,000
83                           $4,000,000
84                          $13,000,000
85                           $1,100,000
86                                 None
87                         $Undisclosed
88                             $2000000
89                             $2000000
90                              $800000
91                             $6000000
92                             $2500000
93                             $9500000
94                            $13000000
95                             $5000000
96                             $8000000
97                             $1000000
98                             Upsparks
99                         $Undisclosed
100                             $200000
101                           $12000000
102                            $1500000
103                            $2000000
104                            $1700000
105                            $5500000
106                            $1000000
107                           $13000000
108                            $5000000
109                            $8000000
110                            $1000000
111                            Upsparks
112                        $Undisclosed
113                             $200000
114                           $12000000
115                            $1500000
116                            $2000000
117                            $1700000
118                            $5500000
119                            $1000000
120                             $400000
121                          $150000000
122                            $4000000
123                        $Undisclosed
124                          $100000000
125                            $6000000
126                            $1000000
127                        $Undisclosed
128                             $500000
129                            $2000000
130                        $Undisclosed
131                            $5500000
132                        $Undisclosed
133                           $15000000
134                            $2000000
135                             $500000
136                            $1000000
137                           $10000000
138                           $40000000
139                           $10000000
140                        $Undisclosed
141                          $225000000
142                            $6700000
143                            $1300000
144                           $20000000
145                             $250000
146                        $Undisclosed
147                           $21000000
148                             $400000
149                            $1200000
150                            $5000000
151                           $52000000
152                             $400000
153                            $3800000
154                           $17500000
155                           $42000000
156                            $6000000
157                            $3800000
158                            $2000000
159                            $2300000
160                            $5000000
161                           $20000000
162                            $1000000
163                            $7000000
164                           $30000000
165                            $1000000
166                          $450000000
167                        $Undisclosed
168                           $28000000
169                             $300000
170                            $3500000
171                        $Undisclosed
172                            $8500000
173                           $25000000
174                             $500000
175                            $1700000
176                            $3500000
177                           $25000000
178                             $400000
179                            $1000000
180                           $12000000
181                          $225000000
182                            $3000000
183                           $37000000
184                            $2000000
185                            $2000000
186                          $370000000
187                             $700000
188                            $5000000
189                           $16000000
190                            $2000000
191                             $500000
192                        $Undisclosed
193                        $Undisclosed
194                             $200000
195                           $10000000
196                            $2000000
197                             $100000
198                           $44000000
199                            $1000000
200                             $500000
201                           $20000000
202                           $10000000
203                            $1700000
204                            $3500000
205                             $300000
206                           $20000000
207                        $Undisclosed
208                             $770000
209                            $1200000
210                        $Undisclosed
211                          $125000000
212                           $35000000
213                           $40000000
214                           $40000000
215                           $50000000
216                            $4900000
217                          $145000000
218                           $22000000
219                           $10000000
220                           $13000000
221                           $10000000
222                           $10000000
223                           $70000000
224                          $100000000
225                            $6700000
226                           $30000000
227                            $7000000
228                            $5000000
229                            $6600000
230                           $32000000
231                          $150000000
232                           $24000000
233                             $700000
234                        $Undisclosed
235                             $200000
236                            $1500000
237                            $1300000
238                            $1000000
239                             $725000
240                             $500000
241                             $461000
242                            Series C
243                            $6600000
244                           $32000000
245                          $150000000
246                           $24000000
247                             $700000
248                        $Undisclosed
249                             $200000
250                            $1500000
251                            $1300000
252                            $1000000
253                             $725000
254                             $500000
255                             $461000
256                            Series C
257                                Seed
258                           $96000000
259                            $5000000
260                           $70000000
261                            $5000000
262                            $4000000
263                           $32000000
264                           $60000000
265                            $7000000
266                           $20000000
267                          $500000000
268                          $266000000
269                            $4500000
270                            $1200000
271                            $4000000
272                             $300000
273                             $200000
274                            $9500000
275                            $1200000
276                          $325000000
277                          $100000000
278                            $6500000
279                            $4000000
280                            $1600000
281                             $150000
282                             $400000
283                             $225000
284                            $5000000
285                          $100000000
286                           $10000000
287                           $85000000
288                           $40000000
289                             $200000
290                             $235000
291                             $260000
292                            $7000000
293                           $30000000
294                            $2900000
295                           $12000000
296                           $53000000
297                            $3500000
298                             $700000
299                            $3000000
300                            $1000000
301                        $Undisclosed
302                            $3000000
303                            $1100000
304                        $Undisclosed
305                        $Undisclosed
306                           $86000000
307                             $130000
308                            $$100,00
309                          $111000000
310                           $37000000
311                            $6000000
312                             $265000
313                            $1000000
314                           $76000000
315                         $30,000,000
316                         Undisclosed
317                        $100,000,000
318                            $200,000
319                         Undisclosed
320                          $2,000,000
321                         Undisclosed
322                          $4,000,000
323                         $75,000,000
324                          $1,000,000
325                         Undisclosed
326                          $3,800,000
327                          $1,500,000
328                            $800,000
329                         $15,000,000
330                          $3,000,000
331                          $2,000,000
332                          $1,000,000
333                        $100,000,000
334                         Undisclosed
335                         $12,000,000
336                         Undisclosed
337                            $100,000
338                          $1,600,000
339                        $100,000,000
340                            $260,000
341                          $2,000,000
342                            $300,000
343                         $30,000,000
344                            $400,000
345                         Undisclosed
346                      $1,000,000,000
347                            $200,000
348                            $400,000
349                          $5,000,000
350                         $15,000,000
351                          $1,000,000
352                         $10,000,000
353                          $1,000,000
354                          $2,000,000
355                         $10,000,000
356                            $200,000
357                          $1,000,000
358                            $600,000
359                         $10,000,000
360                          $6,000,000
361                         $18,000,000
362                          $2,200,000
363                            $150,000
364                         $40,000,000
365                        $120,000,000
366                            $500,000
367                         Undisclosed
368                         $20,000,000
369                            $350,000
370                          $1,000,000
371                            $200,000
372                         $95,000,000
373                          $4,100,000
374                          $5,200,000
375                         $10,000,000
376                         Undisclosed
377                          $5,000,000
378                          $4,000,000
379                         Undisclosed
380                          $8,000,000
381                          $1,400,000
382                          $1,500,000
383                         Undisclosed
384                         Undisclosed
385                         $10,000,000
386                         Undisclosed
387                          $1,000,000
388                          $1,000,000
389                            $300,000
390                          $1,000,000
391                          $9,000,000
392                          $3,000,000
393                         Undisclosed
394                          $5,000,000
395                          $2,000,000
396                          $6,000,000
397                         $40,000,000
398                          $2,000,000
399                          $1,000,000
400                          $2,600,000
401                          $6,000,000
402                          $1,600,000
403                          $2,000,000
404                            $900,000
405                            $250,000
406                         Undisclosed
407                         $10,000,000
408                         $16,000,000
409                          $2,500,000
410                          $7,000,000
411                         $15,000,000
412                         $30,000,000
413                         $10,000,000
414                          $1,500,000
415                          $1,000,000
416                          $1,000,000
417                          $2,000,000
418                            $300,000
419                          $1,500,000
420                          $3,000,000
421                         $15,000,000
422                         $11,000,000
423                          $6,000,000
424                          $1,000,000
425                          $7,000,000
426                        $280,000,000
427                         $50,000,000
428                          $3,000,000
429                         Undisclosed
430                         Undisclosed
431                            $200,000
432                          $1,800,000
433                          $5,000,000
434                         $14,300,000
435                          $4,000,000
436                         $10,000,000
437                         Undisclosed
438                            $300,000
439                            $500,000
440                          $4,000,000
441                         $81,000,000
442                          $1,000,000
443                          $1,300,000
444                        $100,000,000
445                          $2,000,000
446                          $5,000,000
447                            $300,000
448                          $8,200,000
449                         $20,000,000
450                            $200,000
451                          $7,000,000
452                         Undisclosed
453                          $4,000,000
454                            $100,000
455                            $500,000
456                         $70,000,000
457                            $720,000
458                          $3,000,000
459                            $3000000
460                           $15000000
461                             $600000
462                           $10000000
463                            $9000000
464                            $1000000
465                           $10000000
466                            $5000000
467                            $1800000
468                            $6000000
469                             $300000
470                            $1500000
471                            $2000000
472                            $1000000
473                            $4000000
474                           $40000000
475                            $1600000
476                            $2000000
477                            $2000000
478                            $5000000
479                             $300000
480                             $330000
481                            $1000000
482                           $53000000
483                            $6000000
484                             $800000
485                        $undisclosed
486                          $200000000
487                            $1000000
488                            $2000000
489                           $50000000
490                           $36000000
491                        $undisclosed
492                             $300000
493                             $200000
494                            $1000000
495                            $5000000
496                           $67000000
497                            $2000000
498                        $undisclosed
499                            $2500000

In [40]:
# This on the other hand has a lot of missing values

combined_data['Amount($)']

0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
5                NaN
6                NaN
7                NaN
8                NaN
9                NaN
10               NaN
11               NaN
12               NaN
13               NaN
14               NaN
15               NaN
16               NaN
17               NaN
18               NaN
19               NaN
20               NaN
21               NaN
22               NaN
23               NaN
24               NaN
25               NaN
26               NaN
27               NaN
28               NaN
29               NaN
30               NaN
31               NaN
32               NaN
33               NaN
34               NaN
35               NaN
36               NaN
37               NaN
38               NaN
39               NaN
40               NaN
41               NaN
42               NaN
43               NaN
44               NaN
45               NaN
46               NaN
47               NaN
48               NaN
49               NaN
50               NaN
51               NaN
52               NaN
53               NaN
54               NaN
55               NaN
56               NaN
57               NaN
58               NaN
59               NaN
60               NaN
61               NaN
62               NaN
63               NaN
64               NaN
65               NaN
66               NaN
67               NaN
68               NaN
69               NaN
70               NaN
71               NaN
72               NaN
73               NaN
74               NaN
75               NaN
76               NaN
77               NaN
78               NaN
79               NaN
80               NaN
81               NaN
82               NaN
83               NaN
84               NaN
85               NaN
86               NaN
87               NaN
88               NaN
89               NaN
90               NaN
91               NaN
92               NaN
93               NaN
94               NaN
95               NaN
96               NaN
97               NaN
98               NaN
99               NaN
100              NaN
101              NaN
102              NaN
103              NaN
104              NaN
105              NaN
106              NaN
107              NaN
108              NaN
109              NaN
110              NaN
111              NaN
112              NaN
113              NaN
114              NaN
115              NaN
116              NaN
117              NaN
118              NaN
119              NaN
120              NaN
121              NaN
122              NaN
123              NaN
124              NaN
125              NaN
126              NaN
127              NaN
128              NaN
129              NaN
130              NaN
131              NaN
132              NaN
133              NaN
134              NaN
135              NaN
136              NaN
137              NaN
138              NaN
139              NaN
140              NaN
141              NaN
142              NaN
143              NaN
144              NaN
145              NaN
146              NaN
147              NaN
148              NaN
149              NaN
150              NaN
151              NaN
152              NaN
153              NaN
154              NaN
155              NaN
156              NaN
157              NaN
158              NaN
159              NaN
160              NaN
161              NaN
162              NaN
163              NaN
164              NaN
165              NaN
166              NaN
167              NaN
168              NaN
169              NaN
170              NaN
171              NaN
172              NaN
173              NaN
174              NaN
175              NaN
176              NaN
177              NaN
178              NaN
179              NaN
180              NaN
181              NaN
182              NaN
183              NaN
184              NaN
185              NaN
186              NaN
187              NaN
188              NaN
189              NaN
190              NaN
191              NaN
192              NaN
193              NaN
194              NaN
195              NaN
196              NaN
197              NaN
198              NaN
199              NaN
200              NaN
201              NaN
202              NaN
203              NaN
204              NaN
205              NaN
206              NaN
207              NaN
208              NaN
209              NaN
210              NaN
211              NaN
212              NaN
213              NaN
214              NaN
215              NaN
216              NaN
217              NaN
218              NaN
219              NaN
220              NaN
221              NaN
222              NaN
223              NaN
224              NaN
225              NaN
226              NaN
227              NaN
228              NaN
229              NaN
230              NaN
231              NaN
232              NaN
233              NaN
234              NaN
235              NaN
236              NaN
237              NaN
238              NaN
239              NaN
240              NaN
241              NaN
242              NaN
243              NaN
244              NaN
245              NaN
246              NaN
247              NaN
248              NaN
249              NaN
250              NaN
251              NaN
252              NaN
253              NaN
254              NaN
255              NaN
256              NaN
257              NaN
258              NaN
259              NaN
260              NaN
261              NaN
262              NaN
263              NaN
264              NaN
265              NaN
266              NaN
267              NaN
268              NaN
269              NaN
270              NaN
271              NaN
272              NaN
273              NaN
274              NaN
275              NaN
276              NaN
277              NaN
278              NaN
279              NaN
280              NaN
281              NaN
282              NaN
283              NaN
284              NaN
285              NaN
286              NaN
287              NaN
288              NaN
289              NaN
290              NaN
291              NaN
292              NaN
293              NaN
294              NaN
295              NaN
296              NaN
297              NaN
298              NaN
299              NaN
300              NaN
301              NaN
302              NaN
303              NaN
304              NaN
305              NaN
306              NaN
307              NaN
308              NaN
309              NaN
310              NaN
311              NaN
312              NaN
313              NaN
314              NaN
315              NaN
316              NaN
317              NaN
318              NaN
319              NaN
320              NaN
321              NaN
322              NaN
323              NaN
324              NaN
325              NaN
326              NaN
327              NaN
328              NaN
329              NaN
330              NaN
331              NaN
332              NaN
333              NaN
334              NaN
335              NaN
336              NaN
337              NaN
338              NaN
339              NaN
340              NaN
341              NaN
342              NaN
343              NaN
344              NaN
345              NaN
346              NaN
347              NaN
348              NaN
349              NaN
350              NaN
351              NaN
352              NaN
353              NaN
354              NaN
355              NaN
356              NaN
357              NaN
358              NaN
359              NaN
360              NaN
361              NaN
362              NaN
363              NaN
364              NaN
365              NaN
366              NaN
367              NaN
368              NaN
369              NaN
370              NaN
371              NaN
372              NaN
373              NaN
374              NaN
375              NaN
376              NaN
377              NaN
378              NaN
379              NaN
380              NaN
381              NaN
382              NaN
383              NaN
384              NaN
385              NaN
386              NaN
387              NaN
388              NaN
389              NaN
390              NaN
391              NaN
392              NaN
393              NaN
394              NaN
395              NaN
396              NaN
397              NaN
398              NaN
399              NaN
400              NaN
401              NaN
402              NaN
403              NaN
404              NaN
405              NaN
406              NaN
407              NaN
408              NaN
409              NaN
410              NaN
411              NaN
412              NaN
413              NaN
414              NaN
415              NaN
416              NaN
417              NaN
418              NaN
419              NaN
420              NaN
421              NaN
422              NaN
423              NaN
424              NaN
425              NaN
426              NaN
427              NaN
428              NaN
429              NaN
430              NaN
431              NaN
432              NaN
433              NaN
434              NaN
435              NaN
436              NaN
437              NaN
438              NaN
439              NaN
440              NaN
441              NaN
442              NaN
443              NaN
444              NaN
445              NaN
446              NaN
447              NaN
448              NaN
449              NaN
450              NaN
451              NaN
452              NaN
453              NaN
454              NaN
455              NaN
456              NaN
457              NaN
458              NaN
459              NaN
460              NaN
461              NaN
462              NaN
463              NaN
464              NaN
465              NaN
466              NaN
467              NaN
468              NaN
469              NaN
470              NaN
471              NaN
472              NaN
473              NaN
474              NaN
475              NaN
476              NaN
477              NaN
478              NaN
479              NaN
480              NaN
481              NaN
482              NaN
483              NaN
484              NaN
485              NaN
486              NaN
487              NaN
488              NaN
489              NaN
490              NaN
491              NaN
492              NaN
493              NaN
494              NaN
495              NaN
496              NaN
497              NaN
498              NaN
499              NaN
500              NaN
501              NaN
502              NaN
503              NaN
504              NaN
505              NaN
506              NaN
507              NaN
508              NaN
509              NaN
510              NaN
511              NaN
512              NaN
513              NaN
514              NaN
515              NaN
516              NaN
517              NaN
518              NaN
519              NaN
520              NaN
521              NaN
522              NaN
523              NaN
524              NaN
525              NaN
526              NaN
527              NaN
528              NaN
529              NaN
530              NaN
531              NaN
532              NaN
533              NaN
534              NaN
535              NaN
536              NaN
537              NaN
538              NaN
539              NaN
540              NaN
541              NaN
542              NaN
543              NaN
544              NaN
545              NaN
546              NaN
547              NaN
548              NaN
549              NaN
550              NaN
551              NaN
552              NaN
553              NaN
554              NaN
555              NaN
556              NaN
557              NaN
558              NaN
559              NaN
560              NaN
561              NaN
562              NaN
563              NaN
564              NaN
565              NaN
566              NaN
567              NaN
568              NaN
569              NaN
570              NaN
571              NaN
572              NaN
573              NaN
574              NaN
575              NaN
576              NaN
577              NaN
578              NaN
579              NaN
580              NaN
581              NaN
582              NaN
583              NaN
584              NaN
585              NaN
586              NaN
587              NaN
588              NaN
589              NaN
590              NaN
591              NaN
592              NaN
593              NaN
594              NaN
595              NaN
596              NaN
597              NaN
598              NaN
599              NaN
600              NaN
601              NaN
602              NaN
603              NaN
604              NaN
605              NaN
606              NaN
607              NaN
608              NaN
609              NaN
610              NaN
611              NaN
612              NaN
613              NaN
614              NaN
615              NaN
616              NaN
617              NaN
618              NaN
619              NaN
620              NaN
621              NaN
622              NaN
623              NaN
624              NaN
625              NaN
626              NaN
627              NaN
628              NaN
629              NaN
630              NaN
631              NaN
632              NaN
633              NaN
634              NaN
635              NaN
636              NaN
637              NaN
638              NaN
639              NaN
640              NaN
641              NaN
642              NaN
643              NaN
644              NaN
645              NaN
646              NaN
647              NaN
648              NaN
649              NaN
650              NaN
651              NaN
652              NaN
653              NaN
654              NaN
655              NaN
656              NaN
657              NaN
658              NaN
659              NaN
660              NaN
661              NaN
662              NaN
663              NaN
664              NaN
665              NaN
666              NaN
667              NaN
668              NaN
669              NaN
670              NaN
671              NaN
672              NaN
673              NaN
674              NaN
675              NaN
676              NaN
677              NaN
678              NaN
679              NaN
680              NaN
681              NaN
682              NaN
683              NaN
684              NaN
685              NaN
686              NaN
687              NaN
688              NaN
689              NaN
690              NaN
691              NaN
692              NaN
693              NaN
694              NaN
695              NaN
696              NaN
697              NaN
698              NaN
699              NaN
700              NaN
701              NaN
702              NaN
703              NaN
704              NaN
705              NaN
706              NaN
707              NaN
708              NaN
709              NaN
710              NaN
711              NaN
712              NaN
713              NaN
714              NaN
715              NaN
716              NaN
717              NaN
718              NaN
719              NaN
720              NaN
721              NaN
722              NaN
723              NaN
724              NaN
725              NaN
726              NaN
727              NaN
728              NaN
729              NaN
730              NaN
731              NaN
732              NaN
733              NaN
734              NaN
735              NaN
736              NaN
737              NaN
738              NaN
739              NaN
740              NaN
741              NaN
742              NaN
743              NaN
744              NaN
745              NaN
746              NaN
747              NaN
748              NaN
749              NaN
750              NaN
751              NaN
752              NaN
753              NaN
754              NaN
755              NaN
756              NaN
757              NaN
758              NaN
759              NaN
760              NaN
761              NaN
762              NaN
763              NaN
764              NaN
765              NaN
766              NaN
767              NaN
768              NaN
769              NaN
770              NaN
771              NaN
772              NaN
773              NaN
774              NaN
775              NaN
776              NaN
777              NaN
778              NaN
779              NaN
780              NaN
781              NaN
782              NaN
783              NaN
784              NaN
785              NaN
786              NaN
787              NaN
788              NaN
789              NaN
790              NaN
791              NaN
792              NaN
793              NaN
794              NaN
795              NaN
796              NaN
797              NaN
798              NaN
799              NaN
800              NaN
801              NaN
802              NaN
803              NaN
804              NaN
805              NaN
806              NaN
807              NaN
808              NaN
809              NaN
810              NaN
811              NaN
812              NaN
813              NaN
814              NaN
815              NaN
816              NaN
817              NaN
818              NaN
819              NaN
820              NaN
821              NaN
822              NaN
823              NaN
824              NaN
825              NaN
826              NaN
827              NaN
828              NaN
829              NaN
830              NaN
831              NaN
832              NaN
833              NaN
834              NaN
835              NaN
836              NaN
837              NaN
838              NaN
839              NaN
840              NaN
841              NaN
842              NaN
843              NaN
844              NaN
845              NaN
846              NaN
847              NaN
848              NaN
849              NaN
850              NaN
851              NaN
852              NaN
853              NaN
854              NaN
855              NaN
856              NaN
857              NaN
858              NaN
859              NaN
860              NaN
861              NaN
862              NaN
863              NaN
864              NaN
865              NaN
866              NaN
867              NaN
868              NaN
869              NaN
870              NaN
871              NaN
872              NaN
873              NaN
874              NaN
875              NaN
876              NaN
877              NaN
878              NaN
879              NaN
880              NaN
881              NaN
882              NaN
883              NaN
884              NaN
885              NaN
886              NaN
887              NaN
888              NaN
889              NaN
890              NaN
891              NaN
892              NaN
893              NaN
894              NaN
895              NaN
896              NaN
897              NaN
898              NaN
899              NaN
900              NaN
901              NaN
902              NaN
903              NaN
904              NaN
905              NaN
906              NaN
907              NaN
908              NaN
909              NaN
910              NaN
911              NaN
912              NaN
913              NaN
914              NaN
915              NaN
916              NaN
917              NaN
918              NaN
919              NaN
920              NaN
921              NaN
922              NaN
923              NaN
924              NaN
925              NaN
926              NaN
927              NaN
928              NaN
929              NaN
930              NaN
931              NaN
932              NaN
933              NaN
934              NaN
935              NaN
936              NaN
937              NaN
938              NaN
939              NaN
940              NaN
941              NaN
942              NaN
943              NaN
944              NaN
945              NaN
946              NaN
947              NaN
948              NaN
949              NaN
950              NaN
951              NaN

In [41]:
# As much as it has a lot of missing figures, since when we ran our shape before, it was roughly 2880
# This means that this column has a few figures on it's own

combined_data['Amount($)'].isnull().sum()

2790

In [42]:
# Consolidate amounts into a single standardized column

combined_data['Amount_USD'] = combined_data['Amount'].combine_first(combined_data['Amount($)'])
combined_data.tail()

,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,What it does,Amount($),Industry,Round/Series,Location,About Company,Company_Name,Amount_USD
2874,NaN,NaN,NaN,NaN,NaN,NaN,225000000,NaN,NaN,NaN,"B2B, Business Development, Internet, Marketplace",Series C,"Bangalore, Karnataka, India","Udaan is a B2B trade platform, designed specif...",Udaan,225000000
2875,NaN,NaN,NaN,NaN,NaN,NaN,—,NaN,NaN,NaN,"Tourism, Travel",Series A,"Haryana, Haryana, India",HappyEasyGo is an online travel domain.,Happyeasygo Group,—
2876,NaN,NaN,NaN,NaN,NaN,NaN,7500,NaN,NaN,NaN,"Food and Beverage, Food Delivery, Internet",Seed,"Mumbai, Maharashtra, India",Mombay is a unique opportunity for housewives ...,Mombay,7500
2877,NaN,NaN,NaN,NaN,NaN,NaN,"₹35,000,000",NaN,NaN,NaN,Information Technology,Seed,"Mumbai, Maharashtra, India",Droni Tech manufacture UAVs and develop softwa...,Droni Tech,"₹35,000,000"
2878,NaN,NaN,NaN,NaN,NaN,NaN,35000000,NaN,NaN,NaN,"Biotechnology, Health Care, Pharmaceutical",Series C,"Chennai, Tamil Nadu, India",Welcome to India's most convenient pharmacy!,Netmeds,35000000

In [43]:
combined_data.drop(['Amount', 'Amount($)'], inplace=True, axis =1)
combined_data.head()

,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Stage,What it does,Industry,Round/Series,Location,About Company,Company_Name,Amount_USD
0,2019.0,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First",Pre-series A,NaN,NaN,NaN,NaN,NaN,Unbox Robotics,"$1,200,000"
1,2015.0,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management",None,NaN,NaN,NaN,NaN,NaN,upGrad,"$120,000,000"
2,2012.0,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital",Series D,NaN,NaN,NaN,NaN,NaN,Lead School,"$30,000,000"
3,2015.0,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital",Series C,NaN,NaN,NaN,NaN,NaN,Bizongo,"$51,000,000"
4,2021.0,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal",Seed,NaN,NaN,NaN,NaN,NaN,FypMoney,"$2,000,000"

In [44]:
combined_data.columns

Index(['Founded', 'HeadQuarter', 'Sector', 'What_it_does', 'Founders',
       'Investor', 'Stage', 'What it does', 'Industry', 'Round/Series',
       'Location', 'About Company', 'Company_Name', 'Amount_USD'],
      dtype='object')

Our location looks like it could also use some tweaking. Let's have a look at both the location and headquarter values, we can then drop then one which has most of the missing values

In [45]:
combined_data['Location'].isnull().sum()

2353

In [46]:
combined_data['HeadQuarter'].isnull().sum()

640

Alternatively, instead of dropping the location column, we can split the headquarter bit in the location column and merge it with the headquarter column

In [47]:
# Split the location column to give part of the string as the headquarter 

combined_data[['City', 'Remaining_Location']] = combined_data['Location'].str.split(pat =',', n = 1, expand=True)

combined_data.tail()

,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Stage,What it does,Industry,Round/Series,Location,About Company,Company_Name,Amount_USD,City,Remaining_Location
2874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"B2B, Business Development, Internet, Marketplace",Series C,"Bangalore, Karnataka, India","Udaan is a B2B trade platform, designed specif...",Udaan,225000000,Bangalore,"Karnataka, India"
2875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Tourism, Travel",Series A,"Haryana, Haryana, India",HappyEasyGo is an online travel domain.,Happyeasygo Group,—,Haryana,"Haryana, India"
2876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Food and Beverage, Food Delivery, Internet",Seed,"Mumbai, Maharashtra, India",Mombay is a unique opportunity for housewives ...,Mombay,7500,Mumbai,"Maharashtra, India"
2877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Information Technology,Seed,"Mumbai, Maharashtra, India",Droni Tech manufacture UAVs and develop softwa...,Droni Tech,"₹35,000,000",Mumbai,"Maharashtra, India"
2878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Biotechnology, Health Care, Pharmaceutical",Series C,"Chennai, Tamil Nadu, India",Welcome to India's most convenient pharmacy!,Netmeds,35000000,Chennai,"Tamil Nadu, India"

In [48]:
# Drop the redundant columns

combined_data.drop(['Remaining_Location', 'Location'], axis = 1, inplace = True, errors = 'ignore')
combined_data.head()

,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Stage,What it does,Industry,Round/Series,About Company,Company_Name,Amount_USD,City
0,2019.0,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First",Pre-series A,NaN,NaN,NaN,NaN,Unbox Robotics,"$1,200,000",NaN
1,2015.0,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management",None,NaN,NaN,NaN,NaN,upGrad,"$120,000,000",NaN
2,2012.0,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital",Series D,NaN,NaN,NaN,NaN,Lead School,"$30,000,000",NaN
3,2015.0,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital",Series C,NaN,NaN,NaN,NaN,Bizongo,"$51,000,000",NaN
4,2021.0,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal",Seed,NaN,NaN,NaN,NaN,FypMoney,"$2,000,000",NaN

In [49]:
combined_data.columns

Index(['Founded', 'HeadQuarter', 'Sector', 'What_it_does', 'Founders',
       'Investor', 'Stage', 'What it does', 'Industry', 'Round/Series',
       'About Company', 'Company_Name', 'Amount_USD', 'City'],
      dtype='object')

Combine both the HeadQuarter column and the City column and rename it as State column to contain both HeadQuarter and City column

In [53]:
combined_data['State'] = combined_data['HeadQuarter'].combine_first(combined_data['City'])
combined_data.head()

,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Stage,What it does,Industry,Round/Series,About Company,Company_Name,Amount_USD,City,State
0,2019.0,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First",Pre-series A,NaN,NaN,NaN,NaN,Unbox Robotics,"$1,200,000",NaN,Bangalore
1,2015.0,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management",None,NaN,NaN,NaN,NaN,upGrad,"$120,000,000",NaN,Mumbai
2,2012.0,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital",Series D,NaN,NaN,NaN,NaN,Lead School,"$30,000,000",NaN,Mumbai
3,2015.0,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital",Series C,NaN,NaN,NaN,NaN,Bizongo,"$51,000,000",NaN,Mumbai
4,2021.0,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal",Seed,NaN,NaN,NaN,NaN,FypMoney,"$2,000,000",NaN,Gurugram

In [56]:
# Drop redundant columns

combined_data.drop(['HeadQuarter', 'City'], axis=1, inplace=True, errors = 'ignore')
combined_data.head()

,Founded,Sector,What_it_does,Founders,Investor,Stage,What it does,Industry,Round/Series,About Company,Company_Name,Amount_USD,State
0,2019.0,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First",Pre-series A,NaN,NaN,NaN,NaN,Unbox Robotics,"$1,200,000",Bangalore
1,2015.0,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management",None,NaN,NaN,NaN,NaN,upGrad,"$120,000,000",Mumbai
2,2012.0,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital",Series D,NaN,NaN,NaN,NaN,Lead School,"$30,000,000",Mumbai
3,2015.0,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital",Series C,NaN,NaN,NaN,NaN,Bizongo,"$51,000,000",Mumbai
4,2021.0,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal",Seed,NaN,NaN,NaN,NaN,FypMoney,"$2,000,000",Gurugram

In [57]:
combined_data['Stage'].isnull().sum()

1464

In [59]:
combined_data['Round/Series'].isnull().sum()

2353

Similarly, we can combine the Stage and Round/Series column to obtain the Funding_Rounds column

In [61]:

combined_data['Funding_Rounds'] = combined_data['Stage'].combine_first(combined_data['Round/Series'])
combined_data.tail()

,Founded,Sector,What_it_does,Founders,Investor,Stage,What it does,Industry,Round/Series,About Company,Company_Name,Amount_USD,State,Funding_Rounds
2874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"B2B, Business Development, Internet, Marketplace",Series C,"Udaan is a B2B trade platform, designed specif...",Udaan,225000000,Bangalore,Series C
2875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Tourism, Travel",Series A,HappyEasyGo is an online travel domain.,Happyeasygo Group,—,Haryana,Series A
2876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Food and Beverage, Food Delivery, Internet",Seed,Mombay is a unique opportunity for housewives ...,Mombay,7500,Mumbai,Seed
2877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Information Technology,Seed,Droni Tech manufacture UAVs and develop softwa...,Droni Tech,"₹35,000,000",Mumbai,Seed
2878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Biotechnology, Health Care, Pharmaceutical",Series C,Welcome to India's most convenient pharmacy!,Netmeds,35000000,Chennai,Series C

In [64]:
#Drop redundant columns

combined_data.drop(['Stage', 'Round/Series'], axis=1, inplace=True, errors='ignore')
combined_data.tail()

,Founded,Sector,What_it_does,Founders,Investor,What it does,Industry,About Company,Company_Name,Amount_USD,State,Funding_Rounds
2874,NaN,NaN,NaN,NaN,NaN,NaN,"B2B, Business Development, Internet, Marketplace","Udaan is a B2B trade platform, designed specif...",Udaan,225000000,Bangalore,Series C
2875,NaN,NaN,NaN,NaN,NaN,NaN,"Tourism, Travel",HappyEasyGo is an online travel domain.,Happyeasygo Group,—,Haryana,Series A
2876,NaN,NaN,NaN,NaN,NaN,NaN,"Food and Beverage, Food Delivery, Internet",Mombay is a unique opportunity for housewives ...,Mombay,7500,Mumbai,Seed
2877,NaN,NaN,NaN,NaN,NaN,NaN,Information Technology,Droni Tech manufacture UAVs and develop softwa...,Droni Tech,"₹35,000,000",Mumbai,Seed
2878,NaN,NaN,NaN,NaN,NaN,NaN,"Biotechnology, Health Care, Pharmaceutical",Welcome to India's most convenient pharmacy!,Netmeds,35000000,Chennai,Series C

In [66]:
combined_data['What it does'].isnull().sum()

2790

In [68]:
combined_data['What_it_does'].isnull().sum()

615

In [69]:
combined_data['About Company'].isnull().sum()

2353

Likewise, the same case applies for the What_it_does, What it does and About Company column. They are all merged into the Company_Profile column to obtain a single column

In [70]:
# Drop redundant columns

combined_data['Company_Profile'] = combined_data['What_it_does'].combine_first(combined_data['What it does'].combine_first(combined_data['About Company']))
combined_data.head()

,Founded,Sector,What_it_does,Founders,Investor,What it does,Industry,About Company,Company_Name,Amount_USD,State,Funding_Rounds,Company_Profile
0,2019.0,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First",NaN,NaN,NaN,Unbox Robotics,"$1,200,000",Bangalore,Pre-series A,Unbox Robotics builds on-demand AI-driven ware...
1,2015.0,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management",NaN,NaN,NaN,upGrad,"$120,000,000",Mumbai,NaN,UpGrad is an online higher education platform.
2,2012.0,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital",NaN,NaN,NaN,Lead School,"$30,000,000",Mumbai,Series D,LEAD School offers technology based school tra...
3,2015.0,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital",NaN,NaN,NaN,Bizongo,"$51,000,000",Mumbai,Series C,Bizongo is a business-to-business online marke...
4,2021.0,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal",NaN,NaN,NaN,FypMoney,"$2,000,000",Gurugram,Seed,"FypMoney is Digital NEO Bank for Teenagers, em..."

In [71]:
combined_data.drop(['What_it_does', 'What it does', 'About Company'], axis=1, inplace=True, errors='ignore')
combined_data.tail()

,Founded,Sector,Founders,Investor,Industry,Company_Name,Amount_USD,State,Funding_Rounds,Company_Profile
2874,NaN,NaN,NaN,NaN,"B2B, Business Development, Internet, Marketplace",Udaan,225000000,Bangalore,Series C,"Udaan is a B2B trade platform, designed specif..."
2875,NaN,NaN,NaN,NaN,"Tourism, Travel",Happyeasygo Group,—,Haryana,Series A,HappyEasyGo is an online travel domain.
2876,NaN,NaN,NaN,NaN,"Food and Beverage, Food Delivery, Internet",Mombay,7500,Mumbai,Seed,Mombay is a unique opportunity for housewives ...
2877,NaN,NaN,NaN,NaN,Information Technology,Droni Tech,"₹35,000,000",Mumbai,Seed,Droni Tech manufacture UAVs and develop softwa...
2878,NaN,NaN,NaN,NaN,"Biotechnology, Health Care, Pharmaceutical",Netmeds,35000000,Chennai,Series C,Welcome to India's most convenient pharmacy!

In [72]:
combined_data.columns

Index(['Founded', 'Sector', 'Founders', 'Investor', 'Industry', 'Company_Name',
       'Amount_USD', 'State', 'Funding_Rounds', 'Company_Profile'],
      dtype='object')